#!/bin/bash
echo "Building for MacOS ARM"
cross build --release --target=aarch64-apple-darwin

echo "Building for MacOS x86_64"
cross build --release --target=x86_64-apple-darwin

echo "Building for Windows x86_64"
cross build --release --target=x86_64-pc-windows-gnu

echo "Building for Linux x86_64"
cross build --release --target=x86_64-unknown-linux-gnu

echo "Building for Linux ARMv7"
cross build --release --target=armv7-unknown-linux-gnueabihf